version: '2'
services:
  credit-cards-db:
    image: mysql
    ports:
    - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arqsoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: credit-cards
      MYSQL_HOST: credit-cards-db
  credit-cards-ms:
    #build: .
    image: kmendezp/credit-cards-ms
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3003 -b '0.0.0.0'"
    ports:
      - "3003:3003"
    depends_on:
      - credit-cards-db
